version: '3'
services:

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - ./data:/var/jenkins_home
    networks:
      - app-network
networks:
  app-network:
    driver: bridge